### ISSUE TITLE
Create release 1.0.1 on packagist

### ISSUE THREAD

**Issue by raziel057** [welpdev/icalBundle#4]
Hello,

Would it be possible to create the release corresponding to the tag on packagist?

Thx

**Comment by Nightbr** [comment]
Hello,

this should be automatic... I don't know why it's not sync with packagist. Will dig this up

**Comment by Nightbr** [comment]
Done!
Miss to update the composer.json

![image](https://user-images.githubusercontent.com/4228646/77525982-26940b00-6e8a-11ea-96cf-eab7125f0f8d.png)

**Comment by raziel057** [comment]
Thanks!

Envoyé de mon iPhone
